config/routes.rb
Rails.application.routes.draw do
  root 'terms#index'
  # get 'terms/new'
  # get 'terms/create'
  # get 'terms/edit'
  # get 'terms/update'
  # get 'terms/index'
  # get 'terms/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :terms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/term.rb
class Term < ApplicationRecord
    validates :source_term, presence: true
    validates :target_term, presence: true
    validates :part_of_speech, presence: true
    validates :definition, presence: true,
                            length: { minimum: 5}
    validates :term_type, presence: true
    validates :geographical_usage, presence: true
    validate :geographical_usage_must_be_iso3166_alpha3

    private

    def geographical_usage_must_be_iso3166_alpha3
      country = ISO3166::Country.find_country_by_alpha3(geographical_usage)
      unless country
        errors.add(:geographical_usage, "must be a valid ISO 3166-1 alpha-3 country code")
      end
    end
  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  def new
    @term = Term.new
  end

  def create
    @term = Term.new(term_params)
    if @term.save
      redirect_to terms_path, notice: 'Term was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    
  end

  def update
    if @term.update(term_params)
      redirect_to terms_path, notice: 'Term was successfully edited.'
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def index
    @terms = Term.order('LOWER(source_term)')
  end

  def show
    
  end

  def destroy
    @term.destroy
    redirect_to terms_path, notice: 'Term was successfully deleted.'
  end

  private

  def term_params
    params.require(:term).permit(:source_term, :target_term, :part_of_speech, :definition, :term_type, :geographical_usage)
  end

  def set_term
    @term = Term.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="flash <%= type %>"><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Termbase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
  </head>

  <body>
    <%= turbo_stream_from "flash" %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/terms/_form.html.erb
<%= form_with model: @term, class: "term-form" do |form| %>
  
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prevented this term from being saved:</h2>
      <ul>
        <% @term.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :source_term %>
    <%= form.text_field :source_term, placeholder: 'Enter source term here' %>
  </div>
  
  <div class="field">
    <%= form.label :target_term %>
    <%= form.text_field :target_term, placeholder: 'Enter translation here' %>
  </div>

  <div class="field">
  <%= form.label :part_of_speech %>
  <%= form.select :part_of_speech, options_for_select(['Noun', 'Adjective', 'Verb'], @term.part_of_speech), { include_blank: 'Select Part of Speech' }, { class: 'select-css' } %>
  </div>

  <div class="field">
    <%= form.label :definition %>
    <%= form.text_area :definition, placeholder: 'Short description of the term in English. You can include example usage.' %>
  </div>

  <div class="field">
    <%= form.label :term_type %>
    <%= form.select :term_type, options_for_select(['Legal', 'Healthcare', 'General', 'Product/Technology Name'], @term.term_type), { include_blank: 'Select Term Type' }, { class: 'select-css' } %>
  </div>

    <div class="field">
    <%= form.label :geographical_usage %>
    <%= form.text_field :geographical_usage, placeholder: 'ISO 3166 country codes' %>
  </div>

  <div class="actions">
    <%= form.submit "Submit",
    class: "submit-button",
    data: { turbo_confirm: "Are you sure you want to save?" } %>
  </div>

<% end %>

<div class="back-link">
  <%= link_to 'Back to terms', terms_path, class: "back-button" %>
</div>

app/views/terms/create.html.erb
<h1>Terms#create</h1>
<p>Find me in app/views/terms/create.html.erb</p>

app/views/terms/edit.html.erb
<%= render "form", term: @term %>

app/views/terms/index.html.erb
<div class="page-header">
  <div class="header-content">
    <h1><i class="fas fa-language"></i> Termbase</h1>
    <input type="text" id="searchInput" class="search-bar" placeholder="Search terms...">
  </div>
</div>

<table class="styled-table">
    <thead>
        <tr>
            <th>Source</th>
            <th>Target</th>
            <th>Part of Speech</th>
            <th>Definition</th>
            <th>Type</th>
            <th>Geographical Use</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @terms.each do |term| %>
            <tr>
                <td><%= link_to term.source_term, term_path(term) %></td>
                <td><%= term.target_term %></td>
                <td><%= term.part_of_speech %></td>
                <td><%= term.definition %></td>
                <td><%= term.term_type %></td>
                <td><%= term.geographical_usage %></td>
                <td class="actions">
                    <%= link_to edit_term_path(term), class: "btn edit-button" do %>
                <i class="fas fa-edit"></i>
                <% end %>

                <%= button_to term_path(term),
                            method: :delete,
                            data: { turbo_confirm: "Are you sure you want to delete?" },
                            class: "btn delete-button" do %>
                <i class="fas fa-trash"></i>
                <% end %>
                                
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<div class="new-term-button" draggable="true">
  <%= link_to new_term_path, class: "btn btn-primary" do %>
  <i class="fas fa-plus"></i>
  <% end %>
</div>

app/views/terms/new.html.erb
<%= render "form", term: @term %>

app/views/terms/show.html.erb
<div class="term-details">
  <h2 class="term-show-title">Term Details</h2>
  
  <div class="term-detail">
    <strong>Source Term:</strong>
    <p><%= @term.source_term %></p>
  </div>

  <div class="term-detail">
    <strong>Target Term:</strong>
    <p><%= @term.target_term %></p>
  </div>

  <div class="term-detail">
    <strong>Part of Speech:</strong>
    <p><%= @term.part_of_speech %></p>
  </div>

  <div class="term-detail">
    <strong>Definition:</strong>
    <p><%= @term.definition %></p>
  </div>

  <div class="term-detail">
    <strong>Term Type:</strong>
    <p><%= @term.term_type %></p>
  </div>

  <div class="term-detail">
    <strong>Geographical Usage:</strong>
    <p><%= @term.geographical_usage %></p>
  </div>

  <%= link_to edit_term_path(@term), class: "btn edit-button" do %>
    <i class="fas fa-edit"></i> Edit
  <% end %>

  <div class="back-link">
    <%= link_to terms_path, class: "btn back-button" do %>
      <i class="fas fa-arrow-left"></i> Back
    <% end %>
  </div>
  
</div>

app/views/terms/update.html.erb
<h1>Terms#update</h1>
<p>Find me in app/views/terms/update.html.erb</p>